#!/usr/bin/env zsh

export SHELL=$(which zsh)

export DEFAULT_USER=leeor
export EDITOR=nvim
export VISUAL=nvim

export DIRCOLORS=${HOME}/.dircolors

# less {{{

LESSPIPE=$(which src-hilite-lesspipe.sh 2>/dev/null)
[ -n "$LESSPIPE" ] && export LESSOPEN="| ${LESSPIPE} %s"
less_options=(
  --ignore-case
  --chop-long-lines
  --RAW-CONTROL-CHARS
  --quiet
  --dumb
);
export LESS="${less_options[*]}"
export PAGER='less'

# }}}
