#!/usr/bin/env zsh

export SHELL=$(which zsh)

export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache

# You may need to manually set your language environment
export LANG=en_GB.UTF-8
export LC_ALL=en_GB.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

export DEFAULT_USER=leeor
export EDITOR=nvim
export VISUAL=nvim

# define right prompt, if it wasn't defined by a theme
RPROMPT='$(vi_mode_prompt_info) $(build_rprompt)'

export DIRCOLORS=${HOME}/.dircolors
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# less {{{

# Make less the default pager, add some options and enable syntax highlight using source-highlight
LESSPIPE=`which src-hilite-lesspipe.sh`
[ -n "$LESSPIPE" ] && export LESSOPEN="| ${LESSPIPE} %s"
less_options=(
  # keeping the first two options inactive as defining them globally feels too
	# much, as it is causing side effects for everything using less (e.g., git
	# log)
	#
  # If the entire text fits on one screen, just show it and quit. (Be more
  # like "cat" and less like "more".)
  #--quit-if-one-screen

  # Do not clear the screen first.
  #--no-init

  # Like "smartcase" in Vim: ignore case unless the search pattern is mixed.
  --ignore-case

  # Do not automatically wrap long lines.
  --chop-long-lines

  # Allow ANSI colour escapes, but no other escapes.
  --RAW-CONTROL-CHARS

  # Do not ring the bell when trying to scroll past the end of the buffer.
  --quiet

  # Do not complain when we are on a dumb terminal.
  --dumb
);
export LESS="${less_options[*]}"
export PAGER='less'

# }}}

export NVM_LAZY_LOAD=true
