#!/usr/bin/env zsh

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

HISTFILE=$XDG_CACHE_HOME/zsh/zsh_history
ZGEN_CUSTOM_COMPDUMP=${XDG_CACHE_HOME}/zsh/zcompdump

# define right prompt
RPROMPT='$(vi_mode_prompt_info)'
PICO_PROMPT_SYMBOLS_INCLUDE_JOBS=0

unsetopt share_history
# vim: set ft=sh ts=2 sw=2 tw=80 noet :
