#!/usr/bin/env zsh

autoload zmv
alias mmv='noglob zmv -W'

# HTTP Requests. One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done
