# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

fpath=(/usr/local/share/zsh-completions $fpath)

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# User configuration
#export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

# Load the shell dotfiles
for file in $(dirname ${(%):-%x})/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done
unset file

# this is where completion and history will be saved
if [[ ! -d "$XDG_CACHE_HOME/zsh" ]]; then
	mkdir -p $XDG_CACHE_HOME/zsh
fi

# zgen {{{

if [[ ! -f $XDG_CACHE_HOME/zgen/zgen.zsh ]]; then
	git clone https://github.com/tarjoilija/zgen.git "${XDG_CACHE_HOME}/zgen"
fi

ZGEN_DIR=${XDG_CACHE_HOME}/zgen.repos
. $XDG_CACHE_HOME/zgen/zgen.zsh

if ! zgen saved; then
	# Load oh-my-zsh
	zgen oh-my-zsh

	zgen oh-my-zsh plugins/git
	zgen oh-my-zsh plugins/gem
	zgen oh-my-zsh plugins/node
	zgen oh-my-zsh plugins/npm
	zgen oh-my-zsh plugins/ruby
	zgen oh-my-zsh plugins/pip
	zgen oh-my-zsh plugins/python
	zgen oh-my-zsh plugins/web-search
	zgen oh-my-zsh plugins/docker
	zgen oh-my-zsh plugins/go

	zgen loadall <<ENDBUNDLES
		# local plugins
		$(dirname $(readlink ${(%):-%x}))/plugins/vi-mode
		$(dirname $(readlink ${(%):-%x}))/plugins/tmuxifier

		# theme
		$(dirname $(readlink ${(%):-%x}))/themes/pico/pico

		# nvm/npm
		lukechilds/zsh-nvm
		lukechilds/zsh-better-npm-completion

		# syntax highlighting
		zsh-users/zsh-syntax-highlighting
ENDBUNDLES

	if [[ -f "${(%):-%x}.plugins.$(uname)" ]]; then
		while read -r line; do
			zgen ${=line}
		done < "${(%):-%x}.plugins.$(uname)"
	fi

	zgen save
fi

# }}}

# source platform-specific settings
if [[ -a "${(%):-%x}.$(uname)" ]]; then
	source ${(%):-%x}.$(uname)
fi

# source local settings
if [[ -a "${HOME}/.zshrc.local" ]]; then
	source ${HOME}/.zshrc.local
fi
