# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

fpath=(/usr/local/share/zsh-completions $fpath)

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# User configuration
#export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

# Load the shell dotfiles
for file in $(dirname ${(%):-%x})/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done
unset file

# this is where completion and history will be saved
if [[ ! -d "$XDG_CACHE_HOME/zsh" ]]; then
	mkdir -p $XDG_CACHE_HOME/zsh
fi

# antigen {{{

if [[ ! -f $XDG_CACHE_HOME/antigen/antigen.zsh ]]; then
	git clone https://github.com/zsh-users/antigen.git $XDG_CACHE_HOME/antigen
fi

. $XDG_CACHE_HOME/antigen/antigen.zsh

# Load oh-my-zsh
antigen use oh-my-zsh

# set theme
antigen theme leeor/oh-my-zsh-custom themes/agnoster

antigen_plugins=(
	git
	gem
	node
	npm
	ruby
	pip
	python
	web-search
	docker
	go
	'leeor/oh-my-zsh-custom plugins/vi-mode'
	'leeor/oh-my-zsh-custom plugins/tmuxifier'
)

if [[ -f "${(%):-%x}.plugins.$(uname)" ]]; then
	for plugin in $(cat ${(%):-%x}.plugins.$(uname)); do
		antigen_plugins+=(${plugin})
	done
fi

for plugin in $antigen_plugins; do
	antigen bundle ${plugin}
done
unset antigen_plugins

# syntax highlighting
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

# }}}

# source platform-specific settings
if [[ -a "${(%):-%x}.$(uname)" ]]; then
	source ${(%):-%x}.$(uname)
fi

# source local settings
if [[ -a "${HOME}/.zshrc.local" ]]; then
	source ${HOME}/.zshrc.local
fi
